"use client";

// import type { Metadata } from "next";
import Navbar from "@/components/Fragments/Navbar";
import { geistSans, geistMono, lato } from "@/lib/font/fonts";
import "./globals.css";
import { usePathname } from "next/navigation";
import Providers from "@/lib/providers";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const disableNavbar = ["signin", "signup", "admin", "member"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${lato.className} ${lato.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {!disableNavbar.includes(pathname.split("/")[1]) && <Navbar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
